apiVersion: batch/v1
kind: Job
metadata:
  name: exporter
spec:
  completions: 2 # job이 완료되기 위해 필요한 pod의 수
  parallelism: 2 # 동시에 실행될 pod의 수
  template: # 파드 템플릿의 레이블을 기반으로 생성됨
    metadata:
      name: exporter
      labels:
        app: exporter
    spec:
      containers:
      - name: exporter
        image: prom/exporter:latest
        ports:
        - containerPort: 9100
      restartPolicy: OnFailure # job은 기본 재시작 정책(always)를 사용하지 않음. 실패 시에만 재시작하도록 설정